export const data = [
  {
    currency: "USD",
    description: "AMERICAN VANGUARD CORP",
    displaySymbol: "AVD",
    figi: "BBG000DPXVW9",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG001S8KSH7",
    symbol: "AVD",
    symbol2: "",
    type: "Common Stock"
  },
  {
    currency: "USD",
    description: "WIPRO LTD-ADR",
    displaySymbol: "WIT",
    figi: "BBG000BDFT17",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG001S5XGG6",
    symbol: "WIT",
    symbol2: "",
    type: "ADR"
  },
  {
    currency: "USD",
    description: "GAP INC/THE",
    displaySymbol: "GPS",
    figi: "BBG000BKLH74",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG001S5RNN0",
    symbol: "GPS",
    symbol2: "",
    type: "Common Stock"
  },
  {
    currency: "USD",
    description: "QUEST DIAGNOSTICS INC",
    displaySymbol: "DGX",
    figi: "BBG000BN84F3",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG001S9GX43",
    symbol: "DGX",
    symbol2: "",
    type: "Common Stock"
  },
  {
    currency: "USD",
    description: "BUNGE LTD",
    displaySymbol: "BG",
    figi: "BBG000DGPR66",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG001SJ9BG4",
    symbol: "BG",
    symbol2: "",
    type: "Common Stock"
  },
  {
    currency: "USD",
    description: "HUDSON PACIFIC PROPERTIES IN",
    displaySymbol: "HPP",
    figi: "BBG000QC4T33",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG001T6TCN9",
    symbol: "HPP",
    symbol2: "",
    type: "REIT"
  },
  {
    currency: "USD",
    description: "NIO INC - ADR",
    displaySymbol: "NIO",
    figi: "BBG00LPXZB46",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG00LPXZBW5",
    symbol: "NIO",
    symbol2: "",
    type: "ADR"
  },
  {
    currency: "USD",
    description: "AZURE POWER GLOBAL LTD",
    displaySymbol: "AZRE",
    figi: "BBG00BNY1LB5",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG00BNY1LC4",
    symbol: "AZRE",
    symbol2: "",
    type: "Common Stock"
  },
  {
    currency: "USD",
    description: "HAYWARD HOLDINGS INC",
    displaySymbol: "HAYW",
    figi: "BBG00Z9CCRH5",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG00Z9CCSB9",
    symbol: "HAYW",
    symbol2: "",
    type: "Common Stock"
  },
  {
    currency: "USD",
    description: "CORPORATE OFFICE PROPERTIES",
    displaySymbol: "OFC",
    figi: "BBG000BXL4N7",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG001S5XVM6",
    symbol: "OFC",
    symbol2: "",
    type: "REIT"
  },
  {
    currency: "USD",
    description: "NUVEEN AMT-FREE MUNI VAL FD",
    displaySymbol: "NUW",
    figi: "BBG000BB8M05",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG001S6RMX9",
    symbol: "NUW",
    symbol2: "",
    type: "Closed-End Fund"
  },
  {
    currency: "USD",
    description: "STARTEK INC",
    displaySymbol: "SRT",
    figi: "BBG000BNXS80",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG001S9JST4",
    symbol: "SRT",
    symbol2: "",
    type: "Common Stock"
  },
  {
    currency: "USD",
    description: "HUMANA INC",
    displaySymbol: "HUM",
    figi: "BBG000BLKK03",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG001S5S1X6",
    symbol: "HUM",
    symbol2: "",
    type: "Common Stock"
  },
  {
    currency: "USD",
    description: "SKILLSOFT CORP - CW",
    displaySymbol: "SKIL.WS",
    figi: "BBG00PT8DKR7",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "",
    symbol: "SKIL.WS",
    symbol2: "",
    type: "Equity WRT"
  },
  {
    currency: "USD",
    description: "AFRICAN GOLD ACQUISITION COR",
    displaySymbol: "AGAC.U",
    figi: "BBG00YT6S0D5",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG00YT6S189",
    symbol: "AGAC.U",
    symbol2: "",
    type: "Unit"
  },
  {
    currency: "USD",
    description: "NUVEEN MULTI-ASSET INCOME",
    displaySymbol: "NMAI",
    figi: "BBG013NZJC39",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG013NZJD55",
    symbol: "NMAI",
    symbol2: "",
    type: "Closed-End Fund"
  },
  {
    currency: "USD",
    description: "US FOODS HOLDING CORP",
    displaySymbol: "USFD",
    figi: "BBG00C6H6D40",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG00C6H6D59",
    symbol: "USFD",
    symbol2: "",
    type: "Common Stock"
  },
  {
    currency: "USD",
    description: "PITNEY BOWES INC",
    displaySymbol: "PBI",
    figi: "BBG000BQTMJ9",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG001S5V171",
    symbol: "PBI",
    symbol2: "",
    type: "Common Stock"
  },
  {
    currency: "USD",
    description: "VERTICAL CAPITAL INCOME",
    displaySymbol: "VCIF",
    figi: "BBG0038Q3183",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG0038Q3192",
    symbol: "VCIF",
    symbol2: "",
    type: "Closed-End Fund"
  },
  {
    currency: "USD",
    description: "EQUINOR ASA-SPON ADR",
    displaySymbol: "EQNR",
    figi: "BBG000NT0ZZ4",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG001SJ3R93",
    symbol: "EQNR",
    symbol2: "",
    type: "ADR"
  },
  {
    currency: "USD",
    description: "MULTIPLAN CORP-CW25",
    displaySymbol: "MPLN.WS",
    figi: "BBG00SNH0HF1",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "",
    symbol: "MPLN.WS",
    symbol2: "",
    type: "Equity WRT"
  },
  {
    currency: "USD",
    description: "NIKE INC -CL B",
    displaySymbol: "NKE",
    figi: "BBG000C5HS04",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG001S6NTK2",
    symbol: "NKE",
    symbol2: "",
    type: "Common Stock"
  },
  {
    currency: "USD",
    description: "CLASS ACCELERATION A -CW28",
    displaySymbol: "CLAS.WS",
    figi: "BBG00ZHQHW89",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "",
    symbol: "CLAS.WS",
    symbol2: "",
    type: "Equity WRT"
  },
  {
    currency: "USD",
    description: "BUILD-A-BEAR WORKSHOP INC",
    displaySymbol: "BBW",
    figi: "BBG000H8XPS1",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG001SMC9T4",
    symbol: "BBW",
    symbol2: "",
    type: "Common Stock"
  },
  {
    currency: "USD",
    description: "ROYAL BANK OF CANADA",
    displaySymbol: "RY",
    figi: "BBG000BSSC44",
    isin: null,
    mic: "XNYS",
    shareClassFIGI: "BBG001S60869",
    symbol: "RY",
    symbol2: "",
    type: "Common Stock"
  }
];
